#!/bin/bash
# Script para configurar pines del display 2.66"

echo "Configuración de pines para E-Paper 2.66\" (296x152)"
echo "======================================================"
echo ""
echo "Pines del display (conector CN0/CN1):"
echo "  - BUSY  : RD0 (pin 48) - Entrada"
echo "  - DC    : RD1 (pin 49) - Salida"
echo "  - RESET : RD2 (pin 50) - Salida"
echo "  - CS    : RD3 (pin 51) - Salida"
echo ""
echo "Pines SPI:"
echo "  - SCK   : RG6 (pin 23) - Salida"
echo "  - SDO   : RG7 (pin 24) - Salida"
echo "  - SDI   : RG8 (pin 25) - Entrada"
echo ""
echo "Verificar conexiones físicas:"
echo "  1. Alimentación: 3.3V"
echo "  2. GND común"
echo "  3. SPI con resistencias pull-up en líneas? No necesarias"
echo ""
echo "Prueba rápida:"
echo "  - Medir voltaje en VCC del display (debe ser 3.3V)"
echo "  - Verificar BUSY debe estar en HIGH después de inicialización"
